<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LaboratoryERP.Application\LaboratoryERP.Application.csproj" />
    <ProjectReference Include="..\LaboratoryERP.Infrastructure\LaboratoryERP.Infrastructure.csproj" />
    <ProjectReference Include="..\LaboratoryERP.Persistence\LaboratoryERP.Persistence.csproj" />
    <ProjectReference Include="..\LaboratoryERP.Contracts\LaboratoryERP.Contracts.csproj" />
  </ItemGroup>

</Project>
